DELETE FROM USER;
DELETE FROM CLIENT;

ALTER SEQUENCE GLOBAL_SEQ RESTART WITH 100000;

INSERT INTO USER (FIRSTNAME, LASTNAME, SECONDNAME, LOGIN, PASSWORD, EMAIL, ENABLED)
VALUES ('Иван', 'Иванов', 'Иванович', 'admin', 'admin', 'admin@mail.ru', TRUE );

INSERT INTO USER_ROLES (USER_ID, ROLE) VALUES (100000, 'ADMIN');
